# Generated by Django 4.1.3 on 2022-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('codice_fiscal', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('region_of_birth', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
            ],
        ),
    ]
